version: "3"

services:
  redis:
    container_name: statestores-redis
    image: redis
    ports:
        - "6379:6379"
    restart: always 
  app:
    container_name: statestores-app-blazor
    build: "."
    environment:
      "Redis" : "172.26.0.3:6379"
      "URLS"  : "http://+:6005"
    ports:
      - "6005:6005"

