name: Deploy

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Build 
      run: dotnet build --configuration Release
    - name: Test 
      run: dotnet test --configuration Release
    - name: Pack 
      run: dotnet pack --configuration Release -p:PackageVersion=0.0.1
    - name: Add GPR Source
      run: nuget sources add -name "github" -Source https://nuget.pkg.github.com/jandonnermayer/index.json -Username jandonnermayer -Password ${{ secrets.GITHUB_TOKEN }}
    - name: Publish 
      run: dotnet nuget push src/StateStores/bin/Release/netstandard2.0/*.nupkg --source "github"
